### ISSUE TITLE
Adding a separate button for choosing image from gallery.

### ISSUE THREAD

**Issue by Utsav-Mehta** [yashas-hm/Cheque-Scanner#1]

**Comment by yashas-hm** [comment]
Hi thanks for raising the issue.
After installing the app and pressing on the scan check button camera will open.
Look at the bottom left corner there is a button for choosing from gallery.

**Comment by Utsav-Mehta** [comment]
> Hi thanks for raising the issue. After installing the app and pressing on the scan check button camera will open. Look at the bottom left corner there is a button for choosing from gallery.

Adding a separate button below scan button would be better or not?
